
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Toaster } from "@/components/ui/toaster";


const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'ToolsHub4U',
  description: 'Generated by Firebase Studio',
  icons: {
    icon: 'https://picsum.photos/32',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} font-sans antialiased bg-gradient-to-b from-[#0a192f] to-[#1e2a38] text-white`}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
